### ISSUE TITLE
integer overflow in int-benchmark

### ISSUE THREAD

**Issue by travisdowns** [fmtlib/format-benchmark#12]
In int-benchmark the [following code](https://github.com/fmtlib/format-benchmark/blob/2c102e1c1091760457622fec33ecb127875a86c7/src/int-benchmark.cc#L119) is used for generating the random distribution:

~~~
    std::generate(values.begin(), values.end(), []() {
      int scale = std::rand() / 100 + 1;
      return (std::rand() * std::rand()) / scale;
    });
~~~

`std::rand() * std::rand()` may or may not suffer from integer overflow depending on RAND_MAX. On Linux where RAND_MAX is usually 2^31-1, this results in very different results (50% of values are negative) to windows where RAND_MAX is 2^15 (all positive values and smaller values in general). Not sure about OSX.

I guess this is not intentional. Ideally, once would use the same RNG on every platform. I don't know if the 50% negative values is a "feature" or not.

**Comment by vitaut** [comment]
This code originates from karma generate benchmark (https://www.boost.org/doc/libs/1_52_0/libs/spirit/optimization/karma/int_generator.cpp). I think 50% negative is a feature and a PR to make the benchmark more consistent across platforms would be welcome.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/format-benchmark/commit/7ccec775200ef5872ae839c258e0f70f18b7b829. Thanks for reporting!

**Comment by travisdowns** [comment]
Thanks @vitaut and sorry on the delay.

I kind of got blocked when thinking about a PR because it seemed like making it deterministic across platforms would also be a good goal and `<random>` is kind of awkward since IIRC it has no good cross-plat RNGs, so I was like bleh.

**Comment by vitaut** [comment]
> deterministic across platforms would also be a good goal

That would be good and PR is still welcome =). However, the current version shouldn't be too bad - the inputs are not identical but at least distribution is similar.
