### ISSUE TITLE
Why are most digit counts <= 4 in this benchmark?

### ISSUE THREAD

**Issue by expnkx** [fmtlib/format-benchmark#17]
![image](https://user-images.githubusercontent.com/57303909/85240171-2235aa80-b405-11ea-9326-92297015c8c9.png)

Did you try 10 digits? Or std::uint64_t with more digits?

**Comment by vitaut** [comment]
https://www.boost.org/doc/libs/1_52_0/libs/spirit/doc/html/spirit/karma/performance_measurements/numeric_performance/int_performance.html
