### ISSUE TITLE
run test "make bloat-test" error

### ISSUE THREAD

**Issue by viikei** [fmtlib/format-benchmark#21]
1、error1
![image](https://user-images.githubusercontent.com/62841836/108487142-e4618c80-72d9-11eb-9cab-8eff55a0614c.png)

**Comment by vitaut** [comment]
Thanks for reporting but I was not able to repro. The file in question is available here: https://github.com/fmtlib/format-benchmark/blob/master/src/tinyformat.h.

**Comment by viikei** [comment]
when i run "make bloat-test" for tests. the problem is appear. so i think bug for this 
![image](https://user-images.githubusercontent.com/62841836/108653956-b317d500-7502-11eb-8ce1-259854cbe875.png)

**Comment by ilyakurdyukov** [comment]
I have reproduced this on two different machines.

**Comment by vitaut** [comment]
Fixed by #24.
