### ISSUE TITLE
problems with bloat-test (tinyformat, boost)

### ISSUE THREAD

**Issue by ilyakurdyukov** [fmtlib/format-benchmark#22]
Tried to run `$ make bloat-test` on Ubuntu, it fails with an error, it looks like this patch is needed to work properly:

bloat-test.py:
``` patch
 # ifdef USE_TINYFORMAT
-#   include "tinyformat.h"
+#   include "src/tinyformat.h"
 #   define PRINTF tfm::printf
```

And then it fails to compile the boost test (but the dev package for boost is not installed):

#include <boost/format.hpp>

You can properly detect boost availability by using something like this in cmake:

``` cmake
check_cxx_source_compiles("
  #include <boost/format.hpp>
  int main() { return 0; }" HAVE_BOOST)
```

Same for `folly/format.hpp` i guess.

**Comment by ilyakurdyukov** [comment]
Here in bloat-test.py you added the root directory to includes path, but "tinyformat.h" is in "src". 

``` python
  include_dir = '-I' + os.path.dirname(os.path.realpath(__file__))
  command = 'check_call({})'.format(
    [compiler_path, '-std=c++14', '-o', output_filename, include_dir] + sources + flags)
```

**Comment by vitaut** [comment]
Could you submit a PR?

**Comment by ilyakurdyukov** [comment]
I'm added PR for 2 problems, that's easy to fix. Added PR for 2 problems that are easy to fix. The boost and folly detection seems more difficult because I don't know python, you need to add a command line argument with a list of methods to run for bloat-test.py, or detect the same in this script.

**Comment by vitaut** [comment]
Thanks for fixing the tinyformat issue. Currently boost and folly have to be installed but a PR to make them optional is welcome.
